name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm run build

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start minikube
      run: minikube start --driver=docker

    - name: Set IMAGE_NAME env variable
      run: echo "IMAGE_NAME=ghcr.io/${{ github.repository }}:latest" >> $GITHUB_ENV

    - name: Substitute variables and deploy
      run: |
        envsubst < k8s/deployment.yaml | kubectl apply -f -
        kubectl apply -f k8s/service.yaml

    - name: Verify Deployment
      run: kubectl rollout status deployment/my-app
      continue-on-error: true

    - name: Get pods status
      if: always()
      run: kubectl get pods -l app=my-app -o wide

    - name: Describe pods
      if: always()
      run: |
        for pod in $(kubectl get pods -l app=my-app -o jsonpath='{.items[*].metadata.name}'); do
          echo "Describing pod $pod"
          kubectl describe pod $pod
        done

    - name: Get logs from pods
      if: always()
      run: |
        for pod in $(kubectl get pods -l app=my-app -o jsonpath='{.items[*].metadata.name}'); do
          echo "Logs from pod $pod"
          kubectl logs $pod
        done

